### ISSUE TITLE
Not Loading

### ISSUE THREAD

**Issue by TooVeryIcey** [griffenx/CityZen#7]
I Have Vault And My Plugins Use It, But This Comes Up:
19.03 10:25:05 [Server] ERROR - Disabled due to no Vault dependency found!
19.03 10:25:05 [Server] INFO Logging enabled. Check for logs in the Logs folder of your CityZen folder.

**Comment by baph-omet** [comment]
This is likely due to a combination of the following conditions:
1. You have `useEconomy` set to `true` in your `config.yml`.
2. You do not have an Economy plugin set up.

If you have `useEconomy` enabled, you have to have an economy plugin. CityZen shuts itself down if this combination of conditions is true, since it could cause issues when players attempt to buy and sell plots.

I have changed the disable message in CityZen to be a bit more descriptive, but in the meantime, please see if this solves your issue.

**Comment by baph-omet** [comment]
I'm marking this ticket as inactive and closing it due to no response from you in over a week. If this issue is still persisting, please open another ticket.
